### ISSUE TITLE
Bookmarklet links are dead

### ISSUE THREAD

**Issue by mmmeff** [moovweb/harlem_shaker#11]
The links to the bookmarklet for this lib are dead :-1:

**Comment by ianand** [comment]
@mmmeff :( wasn't aware. Which link specifically is broken? let me look into it and get back to you. thanks for the heads up.

**Comment by mmmeff** [comment]
In Readme.md: http://www.moovweb.com/blog/happy-valentines-day-internet-behold-the-harlem-shake-bookmarklet/

**Comment by ianand** [comment]
@mmmeff looks like there was name migration awhile ago and the new link is http://www.moovweb.com/news/happy-valentines-day-internet-behold-the-harlem-shake-bookmarklet/

I've changed the link in the readme.

**Comment by mmmeff** [comment]
![My man!](https://media.giphy.com/media/qPVzemjFi150Q/giphy.gif)
